"""A password-protected PDF gets the same actionable verdict a workbook already gets
(FILES-01, approved as a small maintenance change 2026-09-17).

Before this, an encrypted .xlsx answered `422` with verdict `encrypted` and a sentence
the uploader can act on -- "save it without a password" -- while an encrypted PDF in the
identical situation answered the generic `400 "the cause is not established"`. Same
condition, two different answers, and only one of them tells the user what to do.

THE TRAP THIS FILE EXISTS TO GUARD, because it is what makes the obvious fix wrong
=================================================================================
"Encrypted" means two different things for a PDF, and only one is a refusal. Measured
with pypdf in the shipped image before anything was written:

    user password        is_encrypted=True, decrypt("") -> 0  pages UNREADABLE
    owner password ONLY  is_encrypted=True, decrypt("") -> 1  pages READ FINE

Owner-password PDFs carry usage restrictions (no printing, no copying) and extract
perfectly well today. A fix keyed on `is_encrypted` would have refused a whole class of
files that currently work -- a regression dressed as an improvement. The condition is
therefore "the empty password does not unlock it", and
`test_owner_password_only_pdf_still_extracts` is the test that keeps it that way.

Deliberately NOT built, and not wanted: password storage, password prompting, or any
attempt to break a password. This only names what is wrong.

Fixtures are generated by pypdf at test time. No client content.
"""

import datetime
import io
import os
from concurrent.futures import ThreadPoolExecutor

import jwt
import pytest
from fastapi.testclient import TestClient

from main import app
from app.services.vector_store.async_pg_vector import AsyncPgVector
from app.utils.document_loader import (
    EncryptedDocumentError,
    SafePyPDFLoader,
)

_SECRET = "test_key"
PDF = "application/pdf"


def _pdf(user_password=None, owner_password=None, pages=1, text_hint=None):
    """A real PDF built by pypdf. `text_hint` is unused for blank pages but keeps the
    intent readable at the call site."""
    from pypdf import PdfWriter

    w = PdfWriter()
    for _ in range(pages):
        w.add_blank_page(width=200, height=200)
    if user_password is not None or owner_password is not None:
        w.encrypt(
            user_password=user_password if user_password is not None else "",
            owner_password=owner_password,
        )
    buf = io.BytesIO()
    w.write(buf)
    return buf.getvalue()


def _hdr(act="write", entity="userA"):
    os.environ["JWT_SECRET"] = _SECRET
    payload = {
        "id": "testuser",
        "tid": "tenantA",
        "ent": [entity],
        "act": [act],
        "exp": datetime.datetime.now(datetime.timezone.utc) + datetime.timedelta(hours=1),
    }
    return {"Authorization": f"Bearer {jwt.encode(payload, _SECRET, algorithm='HS256')}"}


@pytest.fixture()
def client(monkeypatch):
    os.environ["JWT_SECRET"] = _SECRET
    if not hasattr(app.state, "thread_pool") or app.state.thread_pool is None:
        app.state.thread_pool = ThreadPoolExecutor(max_workers=2)
    written = []

    async def rec(self, docs, ids=None, executor=None):
        written.append(list(docs))
        return ids or ["id1"]

    monkeypatch.setattr(AsyncPgVector, "aadd_documents", rec)
    c = TestClient(app)
    c.written = written  # type: ignore[attr-defined]
    return c


def _embed(client, name, data):
    return client.post(
        "/embed",
        data={"file_id": "pdf-1", "entity_id": "userA"},
        files={"file": (name, io.BytesIO(data), PDF)},
        headers=_hdr(),
    )


# ===========================================================================
# The repair
# ===========================================================================


def test_locked_pdf_is_named_as_encrypted_at_the_loader(tmp_path):
    """The verdict is decided at the loader, before parsing -- the same place
    SheetExcelLoader decides encrypted-vs-corrupt from the container."""
    path = tmp_path / "locked.pdf"
    path.write_bytes(_pdf(user_password="userpw"))

    loader = SafePyPDFLoader(str(path))
    with pytest.raises(EncryptedDocumentError) as exc:
        list(loader.lazy_load())

    assert exc.value.verdict == "encrypted"
    message = str(exc.value).lower()
    assert "password-protected" in message
    assert "without a password" in message, "the message must say what to DO"


def test_locked_pdf_gets_the_same_422_contract_as_a_locked_workbook(client, tmp_path):
    """Route level: 422, verdict `encrypted`, zero rows -- identical in shape to the
    encrypted-xlsx answer, which is the whole point of the change."""
    r = _embed(client, "locked.pdf", _pdf(user_password="userpw"))

    assert r.status_code == 422, r.text
    detail = r.json()["detail"]
    assert detail["extraction"]["verdict"] == "encrypted"
    assert "without a password" in detail["message"]
    assert client.written == [], "a refused file must write nothing"


def test_the_old_unhelpful_answer_is_gone(client, tmp_path):
    """RED before the change: a locked PDF used to answer 400 'the cause is not
    established', which tells the uploader nothing they can act on."""
    r = _embed(client, "locked.pdf", _pdf(user_password="userpw"))

    assert r.status_code != 400
    assert "cause is not established" not in r.text


# ===========================================================================
# The regression this change could easily have caused
# ===========================================================================


def test_owner_password_only_pdf_still_extracts(client, tmp_path):
    """THE GUARD. An owner-password PDF is readable -- it only restricts printing and
    copying. It extracts today, and must keep extracting.

    A fix keyed on `is_encrypted` alone passes every test above and silently breaks
    this one. That is exactly why this test exists.
    """
    data = _pdf(user_password="", owner_password="ownerpw")

    loader = SafePyPDFLoader(str(tmp_path / "x.pdf"))  # noqa: F841 - loader path below
    path = tmp_path / "owner.pdf"
    path.write_bytes(data)

    # It must not raise at the loader...
    pages = list(SafePyPDFLoader(str(path)).lazy_load())
    assert pages, "an owner-password PDF must still yield pages"

    # ...and it must not be refused as encrypted at the route. A blank page has no
    # text, so the honest answer is the empty-extraction 422 -- NOT `encrypted`.
    r = _embed(client, "owner.pdf", data)
    detail = r.json().get("detail")
    verdict = detail.get("extraction", {}).get("verdict") if isinstance(detail, dict) else None
    assert verdict != "encrypted", (
        "an owner-password PDF was refused as password-protected; it is readable and "
        f"must not be. got {r.status_code}: {r.text}"
    )


def test_plain_pdf_is_untouched(tmp_path):
    """The ordinary case must not acquire a new failure mode."""
    path = tmp_path / "plain.pdf"
    path.write_bytes(_pdf())

    pages = list(SafePyPDFLoader(str(path)).lazy_load())
    assert pages, "a plain PDF must still load"


def test_an_inconclusive_check_never_invents_a_verdict(tmp_path, monkeypatch):
    """If the pre-check itself fails, it must stay silent and let the parser answer.
    A probe that did not work is not evidence that a file is encrypted."""
    path = tmp_path / "plain.pdf"
    path.write_bytes(_pdf())

    import app.utils.document_loader as dl

    def boom(*a, **kw):
        raise RuntimeError("probe exploded")

    monkeypatch.setattr(dl, "PdfReader", boom)

    # No EncryptedDocumentError -- the real loader still runs and succeeds.
    pages = list(SafePyPDFLoader(str(path)).lazy_load())
    assert pages
