"""Route-level proof for the LAST caller-facing `str(e)` on the file-intake surface:
the `/text` outer exception handler (FILES-01 F2).

Why this file exists at all, and why it is a ROUTE test rather than a unit test
==============================================================================
KI-02 SP-01.10 routed the `load_file_content` seam through `describe_failure`, and
SP-01.13 did the same for the upload-save path. SP-01.13 ALSO changed the `/text`
outer handler and then **deliberately reverted it**, because the branch is reachable
only through the full route -- entitlement, path validation and request state all
have to be satisfied before the `try` block runs -- and a change no test could turn
red is not shippable. That judgement was right; this file supplies the missing
harness rather than arguing with it.

What is still unprotected there, established by reading the route and proven below
==================================================================================
Inside `/text`'s `try` block, `save_upload_file_async` and `load_file_content` now
raise `HTTPException` and are re-raised untouched by the `except HTTPException`
branch. Two calls are NOT behind either seam:

  * `os.makedirs(os.path.dirname(validated_temp_file_path), ...)` -- a permission or
    disk failure here raises a bare `OSError` whose `str()` contains OUR temp path.
  * `extract_text_from_documents(data, file_ext)` -- any failure raises raw.

Both land in `except Exception` and are echoed to the caller as
`f"Error during text extraction: {str(e)}"`. That is the leak, and it is also a
mis-attribution: every one of those failures is answered `400`, telling the caller
their file is bad and telling Core's listener not to retry, for faults that are ours.

The marker convention
=====================
Injected exceptions carry `_MARKER`, a string that could only have come from the
exception's own text. Asserting `_MARKER not in response` is a stronger claim than
asserting some particular sentence IS present: it cannot pass by accident and it
cannot be satisfied by a reworded message.

Everything here is SYNTHETIC -- generated bytes and injected exceptions. No client
content, no network, no database. The vector store is simulated and every insert
attempt is recorded, so "nothing was written" is asserted against actual calls
rather than assumed from a status code.
"""

import datetime
import io
import os
import re
from concurrent.futures import ThreadPoolExecutor

import jwt
import pytest
from fastapi.testclient import TestClient

from main import app
from app.constants import ERROR_MESSAGES
from app.routes import document_routes
from app.services.vector_store.async_pg_vector import AsyncPgVector

_SECRET = "test_key"

# A token that can only have travelled out of an exception's own message, plus an
# internal-looking path of the exact shape `_make_unique_temp_path` produces.
_MARKER = "FILES01-INTERNAL-MARKER-9fce21ab"
_FAKE_INTERNAL_PATH = "/tmp/uploads/tenantA/q4-forecast_0123456789abcdef.xlsx"

# `describe_failure` hands the caller a 12-hex reference tying the answer to the log.
_REFERENCE = re.compile(r"Reference: [0-9a-f]{12}\.")


def _hdr(ent, act, tid="tenantA", uid="testuser"):
    os.environ["JWT_SECRET"] = _SECRET
    payload = {
        "id": uid,
        "tid": tid,
        "ent": ent,
        "act": act,
        "exp": datetime.datetime.now(datetime.timezone.utc)
        + datetime.timedelta(hours=1),
    }
    return {"Authorization": f"Bearer {jwt.encode(payload, _SECRET, algorithm='HS256')}"}


@pytest.fixture()
def client(monkeypatch):
    """TestClient with the vector store SIMULATED and every insert attempt recorded.

    `/text` must never write, on success OR on failure; recording the calls lets the
    tests assert that against reality instead of inferring it from a status code.
    """
    os.environ["JWT_SECRET"] = _SECRET
    if not hasattr(app.state, "thread_pool") or app.state.thread_pool is None:
        app.state.thread_pool = ThreadPoolExecutor(max_workers=2)

    added = []

    async def recording_aadd(self, docs, ids=None, executor=None):
        added.append(list(docs))
        return ids

    monkeypatch.setattr(AsyncPgVector, "aadd_documents", recording_aadd)

    test_client = TestClient(app)
    test_client.inserted_batches = added  # type: ignore[attr-defined]
    return test_client


def _text(
    client,
    filename="notes.txt",
    content=b"hello world",
    *,
    content_type="text/plain",
    entity_id="userA",
    ent=None,
    act=None,
    tid="tenantA",
):
    """Drive the real route with LEGITIMATE authorization inputs.

    The defaults are a request that is allowed: `act=['read']` (what Core mints for
    `/text`) and an entitlement containing the entity being addressed. The error
    branch under test only executes once all of that has passed, which is precisely
    why a unit test could not reach it.
    """
    return client.post(
        "/text",
        data={"file_id": "f-text-1", "entity_id": entity_id},
        files={"file": (filename, io.BytesIO(content), content_type)},
        headers=_hdr(
            ent=ent if ent is not None else [entity_id],
            act=act if act is not None else ["read"],
            tid=tid,
        ),
    )


# ===========================================================================
# The leak itself -- these are the tests that must be RED before the fix
# ===========================================================================


def test_extraction_failure_never_echoes_the_exception_to_the_caller(
    client, monkeypatch
):
    """A failure in `extract_text_from_documents` must not hand the caller our
    exception text -- which here carries an internal path."""

    def boom(documents, file_ext):
        raise ValueError(f"cannot decode column at {_FAKE_INTERNAL_PATH} {_MARKER}")

    monkeypatch.setattr(document_routes, "extract_text_from_documents", boom)

    r = _text(client)

    body = r.text
    assert _MARKER not in body, f"exception text reached the caller: {body}"
    assert _FAKE_INTERNAL_PATH not in body, f"internal path reached the caller: {body}"
    assert "/tmp/uploads" not in body
    # The caller is not left with nothing: a reference ties the answer to the log.
    assert _REFERENCE.search(body), f"no reference for the operator to look up: {body}"


def test_makedirs_permission_failure_does_not_leak_our_temp_path(client, monkeypatch):
    """The first unprotected call in the route. A real `PermissionError` puts our
    own upload directory in `str(e)`; that must not be the caller's answer."""
    real_makedirs = os.makedirs

    def boom(path, *args, **kwargs):
        raise PermissionError(
            13, f"Permission denied: '{os.path.dirname(_FAKE_INTERNAL_PATH)}' {_MARKER}"
        )

    monkeypatch.setattr(document_routes.os, "makedirs", boom)
    try:
        r = _text(client)
    finally:
        monkeypatch.setattr(document_routes.os, "makedirs", real_makedirs)

    body = r.text
    assert _MARKER not in body, f"exception text reached the caller: {body}"
    assert "/tmp/uploads" not in body, f"internal path reached the caller: {body}"
    # Review note: absence-only assertions would also pass for a wrong status or a
    # message with nothing the operator can look up. Pin both.
    assert r.status_code == 503, f"our own directory failing is ours: {r.status_code}"
    assert _REFERENCE.search(body), f"no reference for the operator: {body}"


def test_our_outage_is_retryable_and_does_not_blame_the_file(client, monkeypatch):
    """A `MemoryError` building the text is OUR fault. Answering `400` tells Core's
    listener the file is bad and not to retry -- the exact mis-attribution SP-01.10
    exists to prevent, still live on this route."""

    def boom(documents, file_ext):
        raise MemoryError(f"cannot allocate 4.2 GiB {_MARKER}")

    monkeypatch.setattr(document_routes, "extract_text_from_documents", boom)

    r = _text(client)

    assert r.status_code == 503, (
        f"a service fault was reported as a client fault ({r.status_code}); "
        f"body={r.text}"
    )
    assert _MARKER not in r.text
    assert "not with your file" in r.text


def test_dependency_outage_is_retryable(client, monkeypatch):
    """The production Excel failure's shape, one route over: a missing dependency
    is ours, not the uploader's, and must be retryable after the image is fixed."""

    def boom(documents, file_ext):
        raise ModuleNotFoundError(f"No module named 'msoffcrypto' {_MARKER}")

    monkeypatch.setattr(document_routes, "extract_text_from_documents", boom)

    r = _text(client)

    assert r.status_code == 503, f"got {r.status_code}: {r.text}"
    assert _MARKER not in r.text


# ===========================================================================
# The negative space -- what must NOT change, and what must NOT happen
# ===========================================================================


def test_legitimate_text_extraction_still_succeeds(client):
    """The ordinary authorized path. If the fix broke this, the fix is worthless."""
    r = _text(client, filename="notes.txt", content=b"the quick brown fox")

    assert r.status_code == 200, r.text
    body = r.json()
    assert "the quick brown fox" in body["text"]
    assert body["file_id"] == "f-text-1"
    assert body["filename"] == "notes.txt"


def test_multilingual_utf8_survives_the_route(client):
    """The classifier's protected cases must keep working through `/text`."""
    content = "Ünïcödé — 日本語 — العربية — Ελληνικά".encode("utf-8")
    r = _text(client, filename="multi.txt", content=content)

    assert r.status_code == 200, r.text
    assert "日本語" in r.json()["text"]


def test_text_route_writes_nothing_on_success_or_on_failure(client, monkeypatch):
    """`/text` extracts and returns; it must never create a row. A failed extraction
    must never leave a partial artifact behind either."""
    ok = _text(client, filename="notes.txt", content=b"plain")
    assert ok.status_code == 200, ok.text

    def boom(documents, file_ext):
        raise ValueError(f"nope {_MARKER}")

    monkeypatch.setattr(document_routes, "extract_text_from_documents", boom)
    failed = _text(client)
    assert failed.status_code >= 400

    assert client.inserted_batches == [], (
        f"/text wrote {len(client.inserted_batches)} batch(es) to the vector store"
    )


def test_content_rejection_stays_permanent_and_names_the_format(client):
    """A real unsupported binary keeps its terminal verdict. The fix must not sweep
    honest content verdicts into 'our side, try again' -- that would retry forever a
    file that can never work."""
    png = b"\x89PNG\r\n\x1a\n" + b"\x00" * 64
    r = _text(client, filename="diagram.png", content=png, content_type="image/png")

    assert r.status_code == 422, f"got {r.status_code}: {r.text}"
    assert r.status_code != 503
    detail = r.json()["detail"]
    assert detail["extraction"]["status"] == "unsupported"
    # The verdict names the format rather than guessing at the bytes.
    assert detail["extraction"]["verdict"]


def test_temp_file_is_cleaned_up_even_when_extraction_fails(client, monkeypatch):
    """The `finally` cleanup is part of 'no partial state'. Prove it still runs."""
    seen = {}
    real_cleanup = document_routes.cleanup_temp_file_async

    async def recording_cleanup(path):
        seen["path"] = path
        return await real_cleanup(path)

    def boom(documents, file_ext):
        raise ValueError(f"nope {_MARKER}")

    monkeypatch.setattr(document_routes, "cleanup_temp_file_async", recording_cleanup)
    monkeypatch.setattr(document_routes, "extract_text_from_documents", boom)

    _text(client)

    assert "path" in seen, "the temp file was never cleaned up after a failure"
    assert not os.path.exists(seen["path"])


# ===========================================================================
# Tenant / entitlement boundary -- unchanged by this work, asserted anyway
# ===========================================================================


def test_entity_outside_the_entitlement_is_refused(client):
    """Module access is not file access. A token entitled to userB cannot extract
    text for userA, and the refusal must not describe what it refused."""
    r = _text(client, entity_id="userA", ent=["userB"])

    assert r.status_code == 403, r.text
    assert "userA" not in r.text or "Not authorized" in r.text


def test_write_only_token_cannot_read_text(client):
    """`/text` is a read. A token granted only `write` must not reach the body."""
    r = _text(client, act=["write"])

    assert r.status_code == 403, r.text


def test_missing_tenant_context_is_refused(client):
    """A token without `tid` never reaches the route: the middleware fails closed."""
    r = client.post(
        "/text",
        data={"file_id": "f-text-1", "entity_id": "userA"},
        files={"file": ("notes.txt", io.BytesIO(b"secret"), "text/plain")},
        headers=_hdr(ent=["userA"], act=["read"], tid=None),
    )

    assert r.status_code == 403, r.text
    assert b"secret" not in r.content


def test_text_returns_only_the_callers_own_bytes_and_reads_no_storage(
    client, monkeypatch
):
    """The honest statement of this route's tenant boundary, written after
    MEASURING it rather than assuming it.

    `/text` does not query the vector store at all -- it extracts from the bytes on
    THIS request and returns them. So a token from another tenant that legitimately
    carries `ent=['userA']` gets back only what it just uploaded itself; there is no
    stored tenant content on this route for it to cross into. The boundary that
    actually governs here is the entitlement (asserted above), and the property worth
    pinning is that the route never reads storage -- because that is what would have
    to change for a cross-tenant read to become possible.

    Recorded for Core, who owns the central grant/group/exclusion policy: `tid` is
    verified as PRESENT by the middleware but is not used as a scoping filter on this
    route. That is sound only while the route reads nothing; this test fails if that
    ever stops being true.
    """
    reads = []

    async def recording_get(self, ids, *a, **kw):
        reads.append(ids)
        return []

    monkeypatch.setattr(AsyncPgVector, "get_documents_by_ids", recording_get, raising=False)

    r = _text(client, entity_id="userA", ent=["userA"], tid="tenantB", content=b"mine")

    assert r.status_code == 200, r.text
    assert r.json()["text"] == "mine", "the route returned something other than the caller's own bytes"
    assert reads == [], f"/text read from the vector store: {reads}"
    assert client.inserted_batches == []


def test_unauthenticated_request_is_refused(client):
    """No token at all: fail closed."""
    r = client.post(
        "/text",
        data={"file_id": "f-text-1", "entity_id": "userA"},
        files={"file": ("notes.txt", io.BytesIO(b"secret"), "text/plain")},
    )

    assert r.status_code in (401, 403), r.text
    assert b"secret" not in r.content


# ===========================================================================
# Drift check: an actionable message the route still tries to produce
# ===========================================================================


def test_missing_pandoc_still_tells_the_operator_what_to_install(client, monkeypatch):
    """`/text` carries an explicit special case for a missing pandoc install, and it
    is the only honest, ACTIONABLE answer on this handler -- "contact your
    administrator" beats "the cause is not established".

    The special case lives on the OUTER handler, but the failure it targets is raised
    inside the loader, which SP-01.10 now converts into an `HTTPException` before the
    outer handler ever sees it. If that made the branch unreachable, the actionable
    message was silently lost. This test decides that by driving the real path rather
    than reasoning about it.
    """

    class _PandocMissingLoader:
        def __init__(self, *a, **kw):
            pass

        def lazy_load(self):
            # The REAL type, read out of the shipped image rather than guessed:
            # pypandoc/__init__.py:802 raises OSError, not RuntimeError. An earlier
            # version of this test raised RuntimeError and would have passed against a
            # classifier that could never fire in production.
            raise OSError(
                "No pandoc was found: either install pandoc and add it\n"
                "to your PATH or or call pypandoc.download_pandoc(...)"
            )

    monkeypatch.setattr(
        document_routes, "get_loader", lambda *a, **kw: (_PandocMissingLoader(), True, "epub")
    )

    r = _text(client, filename="book.epub", content=b"PK\x03\x04dummy")

    assert ERROR_MESSAGES.PANDOC_NOT_INSTALLED in r.text, (
        "the actionable missing-pandoc message no longer reaches the caller; "
        f"got {r.status_code}: {r.text}"
    )
    # Permanent, not retryable: no amount of retrying installs pandoc.
    assert r.status_code == 400, r.text


def test_a_filename_cannot_disguise_our_outage_as_a_pandoc_problem(client, monkeypatch):
    """The regression an independent review found in my own first version.

    The pandoc check originally matched `"No pandoc was found" in str(link)` anywhere
    in the cause chain. A save-path `OSError` carries the temp path in its message,
    and that path is built from the UPLOADER'S FILENAME -- so naming a file
    `No pandoc was found.txt` made a genuine, retryable storage outage answer
    `400 install pandoc` on every route sharing this classifier. A retryable fault
    turned permanent by a value the caller chooses.

    This is the shared classifier, so the blast radius was /embed, /local/embed and
    /embed-upload too, not just this route.
    """
    hostile = "No pandoc was found.txt"

    def boom(documents, file_ext):
        # The real shape: an OSError whose message embeds our temp path, which in turn
        # embeds the caller's filename.
        raise PermissionError(
            13, f"Permission denied: '/tmp/uploads/tenantA/{hostile}'"
        )

    monkeypatch.setattr(document_routes, "extract_text_from_documents", boom)

    r = _text(client, filename=hostile, content=b"x")

    assert r.status_code == 503, (
        "a caller-chosen filename turned our outage into a permanent failure; "
        f"got {r.status_code}: {r.text}"
    )
    assert ERROR_MESSAGES.PANDOC_NOT_INSTALLED not in r.text
    assert "not with your file" in r.text


def test_an_unclassified_failure_stays_permanent_and_does_not_claim_it_is_temporary(
    client, monkeypatch
):
    """The positive half of the attribution contract, which the first version of this
    file left unpinned: a review mutation that answered 503 to EVERYTHING passed 14 of
    15 tests. "Our side, safe to try again" for a file that is genuinely unreadable is
    a retry loop that never ends, and it is the mirror image of the harm this lane
    exists to fix.
    """

    def boom(documents, file_ext):
        raise ValueError(f"unparseable structure {_MARKER}")

    monkeypatch.setattr(document_routes, "extract_text_from_documents", boom)

    r = _text(client)

    assert r.status_code == 400, f"an unclassified failure must not be sold as transient: {r.text}"
    assert "not with your file" not in r.text
    assert "cause is not established" in r.text
    assert _MARKER not in r.text
